# Generated by Django 2.2.11 on 2020-09-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('phone', models.CharField(max_length=14, verbose_name='phone')),
                ('subject', models.CharField(max_length=40)),
                ('query', models.TextField(verbose_name='query')),
                ('ref_number', models.CharField(blank=True, max_length=20, verbose_name='ref_number')),
                ('qr_code', models.ImageField(blank=True, upload_to='codes_media')),
            ],
            options={
                'verbose_name': 'ContactForm',
                'verbose_name_plural': 'ContactForms',
            },
        ),
    ]
